### ISSUE TITLE
关于天线的问题

### ISSUE THREAD

**Issue by hougehouge123** [Rango-T10000/Antenna_array_GPS_receiver_USRP_GNSS-SDR#1]
_可以使用无源天线进行接收吗

**Comment by Rango-T10000** [comment]
gnss-sdr推荐使用有源天线，因为gps信号太弱了，使用无源天线固然简单，都不需要Bias-Tee来馈电，但是可能由于信号太弱解不出来。

**Comment by hougehouge123** [comment]
> gnss-sdr推荐使用有源天线，因为gps信号太弱了，使用无源天线固然简单，都不需要Bias-Tee来馈电，但是可能由于信号太弱解不出来。

好的谢谢大佬
